
###  get ransom partner list
POST http://localhost:8080/pet/api/location.php
Content-Type: application/json

{
    "type":"get_random_partner_list",
    "count":"10"
}

> {%
    client.log (response.body);
%}

